################################################################################
user_configuration:
reset_global_node_red:
  icon: mdi:mdi:restore
  name: vider les variables node-red
################################################################################
modules_activation:
  icon: mdi:toogle-switch
  name: Modules
module_lights:
  icon: mdi:lightbulb-group
  name: Lumières
module_heat:
  icon: mdi:radiator
  name: Chauffage
module_water_heat:
  icon: mdi:water-boiler
  name: Eau chaude
module_cover:
  icon: mdi:window-shutter
  name: Volets roulants
module_healty:
  icon: mdi:bottle-tonic-plus
  name: Sport et santé
module_temp_hum:
  icon: mdi:thermometer
  name: Alerte température et humidité
module_ventilation:
  icon: mdi:hvac
  name: Ventilation
module_alarm_clock:
  icon: mdi:alarm
  name: Réveil
module_update:
################################################################################
in_home_zone:
  icon: mdi:exit-run
  name: Dans la maison
in_middle_zone:
  icon: mdi:lock-open-variant-outline
  name: Dans la zone moyenne
in_big_zone:
  name: Dans la grande zone
invitation:
  icon: mdi:account-plus
  name: Mode invitation
################################################################################
heat:
  icon: mdi:radiator
  name: Chauffage
################################################################################  
water_heat_temp:
  icon: mdi:toggle-switch
  name: Activation manuelle
################################################################################
low_light_compensation:
  name: Compensation faible luminosité
  icon: mdi:cloud-off-outline
color_reverse:
    name: Inversion du sens de rotation des couleurs
    icon: mdi:palette
################################################################################
alert_light:
  name: Alerte lumineuse
  icon: mdi:home-thermometer-outline
alert_speaker:
  name: Alerte audio
  icon: mdi:home-thermometer-outline
################################################################################
speaker_day_night_mode:
################################################################################
reveil:
  icon: mdi:alarm
  name: Reveil ambiance
################################################################################  
stores_auto:
  icon: mdi:window-shutter-open
  name: Volets automatiques
stores_status:
################################################################################  
motivation:
  icon: mdi:calendar-month-outline
  name: Activités physiques
motivation_resend:
  icon: mdi:refresh
  name: Renvoyer les objectifs de la semaine
motivation_reset:
  icon: mdi:backup-restore
  name: ⚠️ Recommencer au premier jour ⚠️
################################################################################
update_available_on_lemuriens_coconut:
update_from_lemuriens_coconut: